Repository badgateway/ketting, pull requests merged in 2020-09, with the labels that each got.

#242 Better forms
  package-lock.json
  package.json
  readme.md
  src/action.ts
  src/field.ts
  src/index.ts
  src/state/hal.ts
  src/state/html.ts
  src/state/siren.ts
Labels: enhancement

#243 Prepping 5.2.2 release
  changelog.md
  package-lock.json
  package.json
Labels: enhancement

#244 Release time
  changelog.md
  package-lock.json
  package.json
  src/resource.ts
Labels: dependencies, enhancement

#257 ETag and Last-Modified are content headers.
  src/state/base-state.ts
Labels: enhancement

#258 Release 6.0.2
  changelog.md
  package-lock.json
  package.json
Labels: dependencies

#260 Can't call HalState.action() without triggering an error
  src/state/hal.ts
  src/state/interface.ts
Labels: bug

#259 Add HAL FORMS to accepted HAL mime types
  src/client.ts
  test/integration/get.ts
Labels: enhancement
