Repository badgateway/ketting, pull requests merged in 2020-08, with the labels that each got.

#230 Fixed headers property in `getOptions`
  src/resource.ts
Labels: bug

#234 Call the correct cache updating function.
  src/client.ts
  src/resource.ts
  test/unit/resource.ts
Labels: enhancement

#235 Prepping for new Beta release.
  .eslintrc.json
  changelog.md
  package-lock.json
  package.json
Labels: dependencies, enhancement

#236 Return new State object on `patch` if server respond with 200
  src/resource.ts
Labels: enhancement

#239 Support draft-nottingham-link-hints
  changelog.md
  package-lock.json
  package.json
  src/link.ts
  src/state/hal.ts
Labels: enhancement

#233 Only alter 'User-Agent' if `client.fetcher.advertiseKetting` is true
  src/http/fetcher.ts
Labels: enhancement

#240 Use HalState as a fallback for other JSON formats.
  src/client.ts
Labels: enhancement
