Repository badgateway/ketting, pull requests merged in 2021-01, with the labels that each got.

#333 332: Improvements to the Problem type.
  src/http/error.ts
  test/unit/error.ts
Labels: enhancement

#334 Latest HAL Forms updates
  changelog.md
  package-lock.json
  package.json
  src/state/hal.ts
Labels: enhancement

#335 Another state refactor.
  src/client.ts
  src/follow-promise.ts
  src/index.ts
  src/resource.ts
  src/state/base-state.ts
  src/state/binary.ts
  src/state/collection-json.ts
  src/state/hal.ts
  src/state/head.ts
  src/state/html.ts
  src/state/index.ts
  src/state/interface.ts
  src/state/jsonapi.ts
  src/state/siren.ts
  src/state/text.ts
  src/util/html.web.ts
  src/util/uri.web.ts
  test/integration/follow-jsonapi.ts
  test/unit/cache/forever.ts
  test/unit/cache/never.ts
  test/unit/cache/shortcache.ts
  test/unit/client.ts
  test/unit/follower.ts
  test/unit/state/collection-json.ts
  test/unit/state/hal.ts
  test/unit/state/html.ts
  test/unit/state/jsonapi.ts
  test/unit/state/siren.ts
Labels: enhancement

#336 If a Content-Location appears, store the response body in the cache.
  src/client.ts
  src/middlewares/cache.ts
Labels: enhancement

#343 Don't ignore browser cache when using .get().
  changelog.md
  src/resource.ts
Labels: bug

#344 Unify the URI utility.
  src/util/uri.ts
  src/util/uri.web.ts
  test/unit/state/html.ts
  test/unit/state/siren.ts
Labels: enhancement

#345 Ketting 7 beta release
  changelog.md
  package-lock.json
  package.json
  src/middlewares/cache.ts
  test/unit/resource-events.ts
Labels: dependencies

#347 Remove Prefer-Push functionality.
  changelog.md
  src/follow-promise.ts
  test/unit/follower.ts
Labels: enhancement

#349 Revert "Unify the URI utility."
  src/util/uri.ts
  src/util/uri.web.ts
  test/unit/state/html.ts
  test/unit/state/siren.ts
Labels: bug

#350 prep release
  package-lock.json
  package.json
Labels: dependencies

#351 Using field titles in Siren
  changelog.md
  src/state/siren.ts
Labels: enhancement
